name: povo_denuncia
description: Um novo app para registrar denúncias da cidade

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  sqflite: ^2.3.2
  path: ^1.9.0
  path_provider: ^2.1.2
  google_maps_flutter: ^2.5.0
  image_picker: ^1.0.4
  geocoding: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1  
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  image_path: "assets/icon.png"


flutter:
  uses-material-design: true
